language: python

matrix:
  include:
    - python: 2.7
      os: linux
      env: _REZ_SHELL=bash
    - python: 2.7
      os: osx
      env: _REZ_SHELL=bash

install:
  - 'if [ "$_REZ_SHELL" == "tcsh" ]; then sudo apt-get install tcsh; fi'
  - 'python ./install.py ../rez_install'

script:
  # Running rez tests
  - '../rez_install/bin/rez/rez-selftest -s $_REZ_SHELL'
