config_version : 0

name: %(NAME)s

version: %(VERSION)s

uuid: %(UUID)s

authors:
- %(USER)s

description: >
 Enter description here. Multiline is ok, but make sure that you 
 leave the single leading space on each line, as shown here.

requires:
- python

build_requires:
- doxygen
- doxypy

help: %(BROWSER)s file://!ROOT!/doc/html/index.html

%(TOOLS_YAML)s

commands:
- export PYTHONPATH=$PYTHONPATH:!ROOT!/python
%(BIN_PATH_EXPORT_CMD)s
